### ISSUE TITLE
Add usage examples

### ISSUE THREAD

**Issue by nicolaspanel** [theluk/oxford-speech-js#1]
Hi @theluk 

Thank you for sharing this!

However, it is not clear to me how to use it. Could you add few examples in the readme?

Best regards

**Comment by theluk** [comment]
Hello @nicolaspanel 

unfortunatelly I cannot provide any examples or readmes. 
it is just a fork with minimal changes to support it as npm package. 

you may want to check the original repo or some microsoft cognitive service docs
